# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.69.2"
gem "rubocop-github", "~> 0.20.0"
gem "rubocop-minitest", "~> 0.36.0"
gem "rubocop-performance", "~>1.23.1"
gem "rubocop-rails", "~> 2.29"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 3.3.0"
gem "standard", "~>1.42"
