# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.75.4"
gem "rubocop-github", "~> 0.23.0"
gem "rubocop-minitest", "~> 0.38.0"
gem "rubocop-performance", "~>1.25.0"
gem "rubocop-rails", "~> 2.30"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 3.5.0"
gem "standard", "~>1.47"
